In [2]:
import numpy as np

In [3]:
list = [1,2,3]

In [4]:
arr = np.array(list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
mat = np.array(my_mat)

In [8]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2) #range of number with jump space 2

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.zeros((3,2)) #note the input is in tuple format

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
np.linspace(0,5,10)  #prints 10 numbers from 0 to 5 with equal gaps 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [29]:
np.eye(4) # identical matrics

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.random.rand(9) #prints random intergers around 0 to 1

array([0.04279553, 0.27788974, 0.97493674, 0.79992674, 0.20632073,
       0.28259973, 0.43516908, 0.2836984 , 0.70882629])

In [33]:
np.random.rand(5,5) #2d random numbers of 5*5 with 0 to 1 range

array([[0.80163191, 0.22016223, 0.49078505, 0.5143684 , 0.66508294],
       [0.43832085, 0.68037229, 0.18586941, 0.94742711, 0.97970316],
       [0.71226154, 0.1922475 , 0.68939263, 0.38205187, 0.50452344],
       [0.14833084, 0.58158118, 0.76217931, 0.2014265 , 0.39995329],
       [0.30905106, 0.77871925, 0.17975033, 0.17586261, 0.71486017]])

In [34]:
np.random.randn(3) #prints random integers around 0

array([-0.89986658,  0.62275624,  0.60902857])

In [35]:
np.random.randn(3,4) #2d random numbers of 3*4 around 0  # also note the inputs is not a tuple

array([[-0.51318065,  0.95424187, -0.51023347,  0.17388776],
       [ 0.95218656, -0.61966598, -0.1645541 , -1.28114639],
       [-0.96623702, -0.51252155, -0.01615679,  1.42108951]])

In [36]:
np.random.randint(100) #random number from 1 to 99

18

In [38]:
np.random.randint(1,100,10) # 10 random numbers from 1 to 99

array([96, 27, 18, 97, 66,  5,  4, 19, 31, 10])

In [39]:
arr

array([1, 2, 3])

In [40]:
arr = np.arange(25)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
arr.reshape(5,5) #this is NOT inplace change

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr = np.random.randint(1,100,10)

In [45]:
ranarr

array([47, 38, 99, 29,  2, 53, 89, 64, 41, 31])

In [46]:
ranarr.min()

2

In [49]:
arr.shape

(25,)

In [50]:
ranarr.max()

99

In [51]:
ranarr.argmax() #index of the max number

2

In [52]:
ranarr.argmin() #index of the min number

4

In [53]:
arr = arr.reshape(5,5)

In [54]:
arr.shape # note no paranthesis

(5, 5)

In [55]:
arr.shape() #this will result in error 

TypeError: 'tuple' object is not callable

In [56]:
arr.shape

(5, 5)

In [57]:
arr.dtype

dtype('int32')

In [60]:
arr = np.arange(0,11)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
#broadcasting the data in numpy is different to that of list
arr[0:5] = 100 # the first 5 elements will be assigned to 100 in this array


In [63]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
#slicing
arr[3:]

array([100, 100,   5,   6,   7,   8,   9,  10])

In [72]:
sliced = arr[:6]

In [73]:
sliced

array([100, 100, 100, 100, 100,   5])

In [74]:
# note the below changes will also affect the original array arr as well
sliced[:] = 90  # to assign all values of sliced array to a single value 90

In [75]:
sliced

array([90, 90, 90, 90, 90, 90])

In [76]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [77]:
# to avoid making changes to the original array, use copy method
arr_copy = arr.copy()

In [79]:
arr_copy

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [80]:
arr_copy[:6] = 80

In [81]:
arr_copy

array([80, 80, 80, 80, 80, 80,  6,  7,  8,  9, 10])

In [82]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [83]:
#indexing a 2d array ################################################

In [87]:
arr_2d = np.arange(9).reshape(3,3)

In [88]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
# indexing a 2d array can be done with double brackets or in a single bracket with comma seperator
# to fetch 4 value from the above array with first option

arr_2d[1][1]

4

In [91]:
# to fetch 4 value with comma operator

arr_2d[1,1]

4

In [92]:
# slicing using comma operator
# to fetch only the 0 and 3 values from the above array

arr_2d[:2,0:1]

array([[0],
       [3]])

In [93]:
# conditional selection

In [94]:
arr = np.arange(10)

In [95]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
# to check if arr has values greater 5 

arr>5

# this will provide result as False where the condition is not true

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [98]:
# inline syntax to check the conditional operator

arr[arr>5]

# this will give the list array of items meeting the criteria

array([6, 7, 8, 9])

In [99]:
arr[arr<3]

array([0, 1, 2])

In [100]:
my_list = ['a',1,2,'b']

In [101]:
new_arr = np.array(my_list)

In [102]:
new_arr

array(['a', '1', '2', 'b'], dtype='<U1')

In [103]:
np.linspace? # to get the documentation of a method use ? symbol

In [104]:
np.pi

3.141592653589793

In [111]:
np.Inf?

In [113]:
# video3
# numpy operations 
    # array with array 
    # array with scalar
    # universal array functions

In [114]:
arr = np.arange(11)

In [115]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [117]:
arr+arr # this is one of the diff between numpy and lists

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [118]:
list1 = [n for n in range(10)]
list2 = [n for n in range(10,20)]

In [119]:
list1 + list2 # this is one of the diff between numpy and lists

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [120]:
# when 0/0 is done in numpy , it throws warning not Zerodivisionerror

arr/arr      # here the first index of arr is 0 and it evaluates 0/0 - check the below warning and the result nan

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [122]:
arr *3 #broadcasts *3 to all the elements in the array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [123]:
arr **2 #exponentional

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [124]:
# numpy comes with many universal array functions
# which are essentially mathematical operations

In [125]:
# finding square root
np.sqrt(arr)    # not arr.sqrt()

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [128]:
# sin functions

np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])